name: SimpleReplies
main: jasonwynn10\SimpleReplies\Main
version: 1.0.0
api: 4.0.0
author: "jasonwynn10"
description: "Adds a command to reply to the last person who messaged you"
permissions:
  SimpleReplies.reply:
    default: true
    description: "allows the use of /r"